### ISSUE TITLE
可以剪枝yolov5s吗？

### ISSUE THREAD

**Issue by sbbug** [jiachengjiacheng/Pruned-YOLO#1]
你好，非常感谢您的开源贡献！
请问该版本支持yolov5s的剪枝吗？

**Comment by jiachengjiacheng** [comment]
yolov5s和yolov5l的结构是一样的，区别仅在于depth_multiple和width_multiple。在模型构建的时候depth_multiple和width_multiple会乘在相应的参数上，个人建议是将yolov5s的配置文件(yaml)重写一下，调整 args令其中的depth_multiple=1.0且width_multiple=1.0，接下来就可以直接使用提供的剪枝脚本进行剪枝。

**Comment by sbbug** [comment]
> yolov5s和yolov5l的结构是一样的，区别仅在于depth_multiple和width_multiple。在模型构建的时候depth_multiple和width_multiple会乘在相应的参数上，个人建议是将yolov5s的配置文件(yaml)重写一下，调整 args令其中的depth_multiple=1.0且width_multiple=1.0，接下来就可以直接使用提供的剪枝脚本进行剪枝。

ok，感谢楼主热心解答

**Comment by cLEARLoVE00** [comment]
> 你好，非常感谢你的开源贡献！请问
> 该版本支持yolov5s的剪枝吗？
你好，想问下你的yolov5s裁剪成功了么？方便分享一下经验么

**Comment by jiachengjiacheng** [comment]
> > 你好，非常感谢你的开源贡献！请问
> > 该版本支持yolov5s的剪枝吗？
> > 你好，想问下你的yolov5s裁剪成功了么？方便分享一下经验么

请参考上面的回复~
